trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'ADF Variable Group'
- name: workingDir
  value: $(Build.Repository.LocalPath)/azuredatafactory/src
- name: serviceConnectionDev
  value: 'ado-rg-dmp-data-management-westus-dev-sc'
- name: serviceConnectionQa    
  value: 'ado-rg-dmp-data-management-westus-qa-sc'
- name: serviceConnectionProd
  value: 'ado-rg-dmp-data-management-westus-prod-sc'
- name: dataFactoryNameDev
  value: 'adf-dmp-westus-dev-01'
- name: dataFactoryNameQa
  value: 'adf-dmp-westus-qa-01'
- name: dataFactoryNameProd
  value: 'adf-dmp-westus-prod-01'
- name: resourceGroupNameDev
  value: 'rg-dmp-data-management-westus-dev'
- name: resourceGroupNameQa
  value: 'rg-dmp-data-management-westus-qa'
- name: resourceGroupNameProd
  value: 'rg-dmp-data-management-westus-prod'
 
stages:
- stage: build
  displayName: 'Build Artifacts'
  jobs:
  - job:
    steps:
    # configuring node
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      inputs:
        command: 'install'
        verbose: true
        workingDir: '$(workingDir)'
      displayName: 'Install npm package'

    # validating artifacts
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build validate $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupNameDev)/providers/Microsoft.DataFactory/factories/$(dataFactoryNameDev)'
        workingDir: '$(workingDir)'
      displayName: 'Validate'

    # generating ARM Templates from source code
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build export $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupNameDev)/providers/Microsoft.DataFactory/factories/$(dataFactoryNameDev) artifacts'
        workingDir: '$(workingDir)'
      displayName: 'Generate ARM template'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(workingDir)/artifacts'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/application' 
      displayName: 'Copying application artifact'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)/azuredatafactory/cicd-parameters'
        Contents: '*.*'
        TargetFolder: '$(build.artifactstagingdirectory)/ARMTemplateParameter' 
      displayName: 'Copying CICD ARM Template Parameter Files'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifact: 'datafactory'
        publishLocation: 'pipeline'

- stage: 'DEV_Deployment'
  displayName: 'DEV Deployment'
  dependsOn: build
  variables:
    dataFactoryName: $(dataFactoryNameDev)
  jobs: 
  - deployment: DeployToDevelopment
    pool:
      vmImage: 'windows-latest'
    environment: DEV 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
            inputs:
              source: 'current'
              path: '$(Pipeline.Workspace)'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionDev)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameDev) -DataFactoryName $(dataFactoryNameDev) -predeployment $true -deleteDeployment $false'
              azurePowerShellVersion: 'LatestVersion'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploying ADF Artificats'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(serviceConnectionDev)'
              subscriptionId: $(subscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupNameDev)'
              location: 'westus'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
              csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/DEV_ARMTemplateParametersForFactory.json'
              deploymentMode: 'Incremental'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionDev)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameDev) -DataFactoryName $(dataFactoryNameDev) -predeployment $false -deleteDeployment $true'
              azurePowerShellVersion: 'LatestVersion'

- stage: 'QA_Deploy'
  displayName: 'QA-Deploy'
  dependsOn: DEV_Deployment
  variables:
    dataFactoryName: $(dataFactoryNameQa)
  jobs: 
  - deployment: DeployToQa
    pool:
      vmImage: 'windows-latest'
    environment: QA 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
            inputs:
              source: 'current'
              path: '$(Pipeline.Workspace)'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionQa)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameQa) -DataFactoryName $(dataFactoryNameQa) -predeployment $true -deleteDeployment $false'
              azurePowerShellVersion: 'LatestVersion'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploying ADF Artificats'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(serviceConnectionQa)'
              subscriptionId: $(subscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupNameQa)'
              location: 'westus'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
              csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/QA_ARMTemplateParametersForFactory.json'
              deploymentMode: 'Incremental'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionQa)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameQa) -DataFactoryName $(dataFactoryNameQa) -predeployment $false -deleteDeployment $true'
              azurePowerShellVersion: 'LatestVersion'

- stage: 'PROD_Deploy'
  displayName: 'PROD-Deploy'
  dependsOn: QA_Deploy
  variables:
    dataFactoryName: $(dataFactoryNameProd)
  jobs: 
  - deployment: DeployToPROD
    pool:
      vmImage: 'windows-latest'
    environment: PROD 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
            inputs:
              source: 'current'
              path: '$(Pipeline.Workspace)'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionProd)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameProd) -DataFactoryName $(dataFactoryNameProd) -predeployment $true -deleteDeployment $false'
              azurePowerShellVersion: 'LatestVersion'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploying ADF Artificats'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(serviceConnectionProd)'
              subscriptionId: $(subscriptionId_prod)
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupNameProd)'
              location: 'westus'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
              csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PROD_ARMTemplateParametersForFactory.json'
              deploymentMode: 'Incremental'

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '$(serviceConnectionProd)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/PrePostDeploymentScript.ps1'
              ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json" -ResourceGroupName $(resourceGroupNameProd) -DataFactoryName $(dataFactoryNameProd) -predeployment $false -deleteDeployment $true'
              azurePowerShellVersion: 'LatestVersion'
